Fix error handling

diff --git a/deb-mirror b/deb-mirror
--- a/deb-mirror
+++ b/deb-mirror
@@ -472,14 +472,14 @@ export FUEL_BRANCH
 export BINROOT
 
 if [[ "$DOCKER_MODE" = "true" ]]; then
-	( docker ps -a | grep fuel-createmirror ) && docker rm -f fuel-createmirror 
-	# docker pull ubuntu:latest
-	docker -D run -d --name=fuel-createmirror --net=host -a stdout -a stderr -i -t --privileged -e FUEL_BRANCH=$FUEL_BRANCH -e BINROOT=$BINROOT -e apt_altstate=$apt_altstate -v $BINROOT:$BINROOT:rw -v $apt_altstate:$apt_altstate:rw ubuntu:latest
+        ( docker ps -a | grep fuel-createmirror ) && docker rm -f fuel-createmirror 
+        # docker pull ubuntu:latest
+        docker -D run -d --name=fuel-createmirror --net=host -a stdout -a stderr -i -t --privileged -e FUEL_BRANCH=$FUEL_BRANCH -e BINROOT=$BINROOT -e apt_altstate=$apt_altstate -v $BINROOT:$BINROOT:rw -v $apt_altstate:$apt_altstate:rw ubuntu:latest
         dockerctl shell fuel-createmirror $BINROOT/util/partial_ubuntu.sh || fatal "Cannot calculate list of dependencies"
         # cleanup ubuntu container
         docker rm -f fuel-createmirror
 else
-	$BINROOT/util/partial_ubuntu.sh || fatal "Cannot calculate list of dependencies"
+        $BINROOT/util/partial_ubuntu.sh || fatal "Cannot calculate list of dependencies"
 fi
 
 # Create download lists for deb and udeb
