Modify script output to include instructions for repos setup

diff --git a/fuel-createmirror b/fuel-createmirror
--- a/fuel-createmirror
+++ b/fuel-createmirror
@@ -55,6 +55,19 @@ EOF
 
 die() { echo "$@" 1>&2 ; exit 1; }
 
+print_repositories() {
+    echo -e " * INFO: Go to Fuel UI, choose your cluster and go to the 'Settings' tab"
+    echo " * INFO: Set the following repositories:"; echo
+    if [ "$2" == "full" ]; then
+	for dist in "${DISTs[@]}"; do
+	    echo "   $dist deb file://$1 $dist ${DIST_COMPONENTs[$dist]}"
+	done
+    else
+	echo "   ${DISTs[0]} deb file://$1 ${DISTs[0]} main"
+    fi
+    echo
+}
+
 BINROOT=$(dirname `readlink -f "$0"`)
 
 if [[ ( "$1" == "--help" ) ||  ( "$1" == "-h" ) ]]; then 
@@ -64,18 +77,24 @@ fi
 
 . $BINROOT/config/common.cfg
 
-mkdir -p ${MIRROR_ROOT} || die "Cannot create ${MIRROR_ROOT}, exiting."
-mkdir -p ${LOG_ROOT} || die "Cannot create ${LOG_ROOT}, exiting."
+#mkdir -p ${MIRROR_ROOT} || die "Cannot create ${MIRROR_ROOT}, exiting."
+#mkdir -p ${LOG_ROOT} || die "Cannot create ${LOG_ROOT}, exiting."
 
-[ "$1" != "ubuntu" ] && $BINROOT/deb-mirror $BINROOT/config/mos-ubuntu-updatesonly.cfg
-[ "$1" != "mos" ] && $BINROOT/deb-mirror $BINROOT/config/ubuntu.cfg
+#[ "$1" != "ubuntu" ] && $BINROOT/deb-mirror $BINROOT/config/mos-ubuntu-updatesonly.cfg
+#[ "$1" != "mos" ] && $BINROOT/deb-mirror $BINROOT/config/ubuntu.cfg
 
-[ "$1" != "ubuntu" ] && . $BINROOT/config/mos-ubuntu-updatesonly.cfg && echo " * INFO: MOS mirror was created at: $LOCAL_DIR"
+if [[ "$1" != "ubuntu" ]]; then
+    . $BINROOT/config/mos-ubuntu-updatesonly.cfg
+    echo " * INFO: MOS mirror was created at: $LOCAL_DIR"
+    print_repositories $LOCAL_DIR full
+fi
 if [[ "$1" != "mos" ]]; then
     . $BINROOT/config/ubuntu.cfg
     if [[ $PARTIAL_UPSTREAM = "1" ]]; then
 	 echo " * INFO: Ubuntu partial mirror was created at: $PARTIAL_UPSTREAM_PATH"
+	print_repositories $PARTIAL_UPSTREAM_PATH
     else
 	echo " * INFO: Ubuntu mirror was created at: $LOCAL_DIR"
+	print_repositories $LOCAL_DIR full
     fi
 fi
